### Place Index
GET http://localhost:3000/places.json

### Place Show
GET http://localhost:3000/places/1.json

### Place Post
POST http://localhost:3000/places.json
Content-Type: application/json

{
  "name": "Savemart",
  "address": "Grocery Rd"
}

### Place Patch
PATCH http://localhost:3000/places/1.json
Content-Type: application/json

{
  "address": "Update Dr"
}

### Place Destroy
DELETE http://localhost:3000/places/6